#!/bin/bash

$HOME/.local/bin/slstatus &

pgrep picom > /dev/null && picom &
pgrep mopidy > /dev/null && mopidy &

nitrogen --restore
setxkbmap us colemak -option ctrl:nocaps

while true; do
	$HOME/.local/bin/dwm
	status=$?
	test status -gt 3 && exit 0
done
